### ISSUE TITLE
Crash generating release notes

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#167]
```
2020/11/01 11:25:33 Duration: 0.008617 seconds
2020/11/01 11:25:34 stderr: 2020/11/01 11:25:34 Release [openfaas-incubator/ingress-operator:0.6.4] start: 0001-01-01 00:00:00 +0000 UTC	end: "0001-01-01 00:00:00 +0000 UTC"
2020/11/01 11:25:34 Release notes: "Changelog for :\n\nCommits\n\nGenerated by [Derek](https://github.com/alexellis/derek/)\n"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d2092]

goroutine 1 [running]:
github.com/alexellis/derek/handler.updateRelease(0xc0004128c0, 0x0, 0xc0000b4f20, 0x12, 0xc00014a000, 0x10, 0x0, 0x0, 0xc00019b5c0, 0x54, ...)
	/go/src/github.com/alexellis/derek/handler/release_handler.go:204 +0x62
github.com/alexellis/derek/handler.updateReleaseNotes(0xc0004128c0, 0xc0000b4f20, 0x12, 0xc00014a000, 0x10, 0xc000131fb0, 0x5, 0x0, 0xc0004128c0)
	/go/src/github.com/alexellis/derek/handler/release_handler.go:108 +0xb65
github.com/alexellis/derek/handler.(*UpdatingReleaseHandler).Handle(0xc0000aa400, 0xc000083610, 0xc0000ace60, 0xc000148000, 0xc0000c86e0, 0xc0000ee080, 0xc0003ba4c0, 0xde70b95193631570)
	/go/src/github.com/alexellis/derek/handler/release_handler.go:43 +0x116
main.handleEvent(0xc0000160f4, 0x7, 0xc0000fc000, 0x24f3, 0x3e00, 0xc0000a0120, 0x28, 0xc000102000, 0x68f, 0xc00001602f, ...)
	/go/src/github.com/alexellis/derek/main.go:103 +0x18af
main.main()
	/go/src/github.com/alexellis/derek/main.go:62 +0x1e4
2020/11/01 11:25:34 Success=false, Error=exit status 2
2020/11/01 11:25:34 Out=
2020/11/01 11:27:56 Forking fprocess.
2020/11/01 11:27:56 Query  
2020/11/01 11:27:56 Path  /
2020/11/01 11:27:58 stderr: 2020/11/01 11:27:58 Release [openfaas-incubator/ingress-operator:0.6.4] start: 2020-11-01 11:24:54 +0000 UTC	end: "2020-06-18 14:54:05 +0000 UTC"
2020/11/01 11:27:58 Release notes: "Changelog for 0.6.4:\n* PR #35 Use the ingress domain for the tls secret by @LucasRoesler\n\nCommits\ndf2332dfa1bc46f41bfbdb6d3066d104e3f584ac Use the ingress domain for the tls secret by @LucasRoesler\nf627c24ccb91e21065c1e62ef986743a63e85426 Fix example, move REST example to docs by @alexellis\na4c4ee1ed250a1da6c613ea76f6799da2dd4d234 Update REST API mapping by @alexellis\nd93fe76e30ef1f65b94f1fa32b503f4cca8b9695 Update examples for REST by @alexellis\ne7a6aae212eb150ddc012671f25439ade274304a Add async example by @alexellis\n\nGenerated by [Derek](https://github.com/alexellis/derek/)\n"
2020/11/01 11:27:58 Duration: 2.295807 seconds
2020/11/01 11:27:59 Forking fprocess.
2020/11/01 11:27:59 Query  
2020/11/01 11:27:59 Path  /
2020/11/01 11:27:59 Duration: 0.002734 seconds
```

When I re-tried the web hook for the release, it worked the second time -> https://github.com/openfaas-incubator/ingress-operator/releases/tag/0.6.4

**Comment by alexellis** [comment]
I wonder if this is a timing issue with the release not being detected?
